### ISSUE TITLE
Add align and valign

### ISSUE THREAD

**Issue by Laureatus** [hteumeuleu/caniemail#107]

**Comment by hteumeuleu** [comment]
I added [valign](https://www.caniemail.com/features/html-valign/) today. Need to add `align` now.

**Comment by felixfbecker** [comment]
Would love to know about `align` on `img` given that CSS `float` seems to not be supported in Outlook on Windows

**Comment by hteumeuleu** [comment]
I added [align](https://www.caniemail.com/features/html-align/) today. I'm closing this issue now but feel free to comment if you've got any feedback.
