### ISSUE TITLE
Spark mail client missing

### ISSUE THREAD

**Issue by jag-k** [hteumeuleu/caniemail#111]
Can you add [Spark](https://sparkmailapp.com/) Mail Client in your client list? Or does Spark not have any special features and it is comparable to another client?

**Comment by hteumeuleu** [comment]
It's next in my todo list here: https://github.com/hteumeuleu/caniemail/issues/65. Which version would you be interested in the most? (macOS, iOS, Android?)

**Comment by jag-k** [comment]
macOS and iOS))

**Comment by hteumeuleu** [comment]
Thanks. I'm closing this as I'm tracking it in #65.
