### ISSUE TITLE
Add support of BIMI

### ISSUE THREAD

**Issue by ajabep** [hteumeuleu/caniemail#112]
https://bimigroup.org

**Comment by hteumeuleu** [comment]
So I'm actually interested in testing this but I'm not sure where I should start. Does anyone have a guide on how to set up BIMI? And is there any known particularities in email clients to get it to work? (I see that Gmail is testing it, but not sure how I can optin.)

**Comment by DavidOsipov** [comment]
Try this official website of BIMI working group: https://bimigroup.org/
