### ISSUE TITLE
[HTML] loading attribute on <img>

### ISSUE THREAD

**Issue by husseinalhammad** [hteumeuleu/caniemail#131]
It would great to test and add support data for the [loading attribute on images](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading).

```html
<img src="image.png" loading="lazy" alt="…" width="200" height="200">
```

This was brought up in the emailgeeks slack. @M-J-Robbins ran a quick test on Litmus:

> A quick Litmus test show that some email clients don’t remove the `loading="lazy"` attribute:
>
> - Thunderbird
> - Samsung
> - freenet
> - Outlook mac
> - Applemail
>
> So it might work in some of these, although they might have something else in place that messes with it.
>
> Applemail and Outlook for mac are based on Safari so they won’t work. But the other might, maybe :shrug:

Although Mark's tests show the attribute is supported on some clients and this is a HTML feature, the `loading` attribute should only work when JavaScript is enabled. From MDN:

> Loading is only deferred when JavaScript is enabled. This is an anti-tracking measure, because if a user agent supported lazy loading when scripting is disabled, it would still be possible for a site to track a user's approximate scroll position throughout a session, by strategically placing images in a page's markup such that a server can track how many images are requested and when.

This can be tricky to test on desktop clients, but not impossible on webmail clients. Does the image loading get deferred if a webmail client keeps the attribute (e.g. freenet) when accessed on a JS-enabled browser?

**Comment by M-J-Robbins** [comment]
I did a little testing and Freenet does indeed work with `loading="lazy"` (if the browser supports it and (I'm assuming) if JS is enabled). 

This test was done by looking at image requests with dev tools. For apps it might be easier to look at the image requests from the server point of view.

**Comment by husseinalhammad** [comment]
There's now a basic test for `img[loading]` if anyone would like to expand it and/or test it more thoroughly:
https://github.com/hteumeuleu/caniemail/blob/master/tests/html-loading-attribute.html

**Comment by hteumeuleu** [comment]
I'm closing this for now but feel free to keep the discussions or file a new issue if this needs an update.
