### ISSUE TITLE
Support for display:inline-block

### ISSUE THREAD

**Issue by amulchinock** [hteumeuleu/caniemail#134]
There doesn't appear to be any data on whether this CSS property.

StackOverflow does give some insight into the support for within Gmail and some versions of Outlook: https://stackoverflow.com/questions/49071102/displayinline-block-not-working-outlook-gmail

**Comment by scheinercc** [comment]
There is detailed information on support here (assuming the green ticks include `inline-block`):
https://www.campaignmonitor.com/css/positioning-display/display/
