### ISSUE TITLE
border-radius as shorthand not supported on Outlook.com

### ISSUE THREAD

**Issue by aoxpedition** [hteumeuleu/caniemail#137]
Outlook.com only accepts 1 value for border-radius, so border-radius cannot be used as shorthand for multiple corners. If multiple values are entered the first value is applied to all 4 corners. To set a corner's border-radius individually, one must use the separate properties:
- border-top-left-radius
- border-top-right-radius
- border-bottom-right-radius
- border-bottom-left-radius

Test date: Feb 24 2021
Tested live on outlook.com and inspected html

**Comment by hteumeuleu** [comment]
Interesting! I need to check with what @husseinalhammad recently updated: https://github.com/hteumeuleu/caniemail/pull/133

**Comment by husseinalhammad** [comment]
Ah weird! I didn't see this when I opened #133. @aoxpedition could you share a reduced test case where you see this happening? 

I had another look to check whether there has been an update, but I still see all the following syntaxes working in Outlook.com (live test):

```css
/* 4 values */
border-radius: 10px 40px 40px 10px;

/* 2 values */
border-radius: 40px 10px;

/* 8 values; shorthand for elliptical corners */
border-radius: 27% 73% 70% 30% / 30% 34% 66% 70%;

/* 2 values; shorthand for elliptical corners */
border-radius: 100px / 30px;
```

I only tested on `<div>` elements with inlined styles. So I wonder if support is different on other HTML elements or in embedded styles.

**Comment by aoxpedition** [comment]
Thanks for looking into this. I've tested a few more times and you're right it does work when sending a regular email. I'm having the issue when a message has been forwarded to outlook.com instead of sent directly. Outlook.com must render differently when there's a forward. 

In these tests I tried using both the shorthand for 4 values, and the individual corner properties.

```html
<p><a href="https://www.example.com" style="color:white;display:inline-block; border-radius: 1px 6px 6px 1px;padding:6px;background-color: #1A73E8;">Rounded on right shorthand</a></p>
<p><a href="https://www.example.com" style="color:white;display:inline-block; border-top-left-radius: 1px;border-top-right-radius:6px;border-bottom-right-radius:6px; border-bottom-left-radius:1px;padding:6px;background-color: #1A73E8;">Rounded on right separate</a></p>
```
I first sent myself the links in gmail
Then I forwarded it to my outlook.com account, pasting the html a second time above the forwarded message.

In outlook.com the top email and forwarded email are displayed in separates panes. All links were displayed with 1px radius on all 4 corners.

**Comment by hteumeuleu** [comment]
@aoxpedition I tried to replicate exactly what you did (sending the email to my Gmail account, forwarding it from Gmail desktop webmail to my Outlook.com account while also pasting it a second time) and can't seem to reproduce the problem. In Outlook.com, I do have all the border radiuses correctly showing.

Try to see if the source is correctly sent. (In Outlook.com, you can go to an email > … > View > View message source). My guess is the problem here is the way you forward or copy the email (which is honestly never a good way to test an HTML email), not email clients support.

**Comment by aoxpedition** [comment]
Hi @hteumeuleu I'll add some screenshots of the appearance and source on outlook.com.

The steps I followed for this latest test:
1. I first sent to the google account via Apps Script's Gmail service. 
```html
  <table><tr><td style="font-family: system-ui, Arial, sans-serif">
    <p>Hello test recipient,</p>  
    <p>
      <a href="https://www.example.com" style="border-radius: 1px 6px 6px 1px;color:white;display:inline-block; padding:6px;background-color:#1A73E8;">Rounded on right shorthand</a>
    </p>
    <p>
      <a href="https://www.example.com" style="border-top-left-radius:1px;border-top-right-radius:6px;border-bottom-right-radius:6px; border-bottom-left-radius:1px;color:white;display:inline-block;padding:6px;background-color:#1A73E8;">Rounded on right separate</a>
    </p>
    <p>Best,<br>Sender</p>
  </td></tr></table>
```
2. In Gmail desktop webmail, I selected "forward" 
   - *optional:*  I added the same styled links above the forwarded message (via dev tools since Gmail's WYSIWYG can combine properties into shorthand if the html was pasted in).   
3. Address to outlook.com account
  
**Result:** The forward arrived in the outlook.com inbox and the border-radius shorthand version did not display correctly.  
![border radius ex forwarded to outlook](https://aoxpedition.github.io/email/outlook/img/2021-03-02t19:14:00-outlook-border-radius-.jpg)
  
**Source code** shows that code was sent intact:  
![border radius ex forwarded to outlook source code](https://aoxpedition.github.io/email/outlook/img/2021-03-02t19:14:00-outlook-border-radius-source.jpg)

I agree this isn't the right way to test emails being sent to outlook.com since it displays correctly at first. This forwarded-email test is still useful on its own. Marketing event/webinar invitations that I send are frequently forwarded by sales teams or within companies/agencies so this appearance is likely to happen. 
This also affects replies; Once there is message history, Outlook.com uses a different rendering method. The original styles are preserved in the source code but only the first email (if sent directly, not forwarded, to outlook.com) displays correctly. 

1. Send from Apps Script Gmail service directly to outlook.com
2. In outlook.com desktop webmail, reply to gmail account 
   - Inline styles were preserved and rendered in gmail
3. In Gmail desktop webmail, reply to outlook.com account 
   - Gmail combined separate properties into border-radius shorthand and also converted hex colors to rgb

**Result:** Top (direct email) pane displays correctly, expanded reply pane renders only first value of border-radius shorthand. 4 values are still present in source code.
![border radius ex forwarded to outlook source code](https://aoxpedition.github.io/email/outlook/img/2021-03-02t21:20:00-outlook-border-radius-reply.jpg)

Finally I tested margin, padding, and border-width with similar method. In emails sent directly to outlook.com, the inline styles are output exactly as in the source code. In replies/forwarded email, separate properties are combined into shorthand but it does NOT drop the 2nd-4th values, so it displays correctly.
![border radius ex forwarded to outlook source code](https://aoxpedition.github.io/email/outlook/img/2021-03-02-outlook-m-p-bdw.jpg)

**Comment by hteumeuleu** [comment]
I just tested following your instructions, and indeed I can confirm I reproduce the same issue. I'm not sure what to do with this though. I'd rather not include the behavior when forwarding or replying to emails in caniemail as it brings a whole other level of complexity. Perhaps this is something worth noting on [email-bugs](https://github.com/hteumeuleu/email-bugs/issues) and linking it as an informative note on caniemail?
