### ISSUE TITLE
[Blog] Introducing caniemail.com : Incorrect link to other 

### ISSUE THREAD

**Issue by cvergne** [hteumeuleu/caniemail#14]
Hi 👋 

First, thanks for that tool :)

There is a small typo in the intro blog post with the link to a previous article.

**Where ?** https://www.caniemail.com/news/2019-09-09-introducing-caniemail/

**What ?** The first link _[a proposal for Can I email]_ in first paragraph goes to `http://127.0.0.1:4000/news/2019-03-15-caniemail-a-proposal/`

It should go to `https://www.caniemail.com/news/2019-03-15-caniemail-a-proposal/`

**Comment by hteumeuleu** [comment]
> But it works on my computer!

Whoops, nice catch. I fixed it. Thanks!
