### ISSUE TITLE
Yahoo desktop webmail <style> element

### ISSUE THREAD

**Issue by m-nienberg** [hteumeuleu/caniemail#141]
https://www.caniemail.com/features/html-style/ 
shows full support for the <style> element for Yahoo desktop webmail, but I think there should be a note saying that comments in the <style> section, (but outside a selector) will cause the next selector to be ignored. For example:

```
<head>
<title>style element</title>
<style>
    /* this comment will break the following selector */            
    .test1 {
        color: #fff;
        background-color: #39b54a;
    }
</style>
</head>
```

**Comment by hteumeuleu** [comment]
That's a good idea. I'll add that.

**Comment by hteumeuleu** [comment]
Done: https://www.caniemail.com/features/html-style/#style-element-cite-note-5

Feel free to reopen if you have something to add.
