### ISSUE TITLE
Oulook.com already supports svg

### ISSUE THREAD

**Issue by sjuve** [hteumeuleu/caniemail#142]
Oulook.com already supports svg

**Comment by hteumeuleu** [comment]
Hello, could you be more specific please? [SVG image format](https://www.caniemail.com/features/image-svg/) does work in Outlook.com, but not [embedded SVG](https://www.caniemail.com/features/html-svg/), as stated on Can I email.

**Comment by sjuve** [comment]
Hello

In Outlook webmail in Microsoft 365 you can insert inline an svg image, in the body of the mail or even in the signature. I thought it was the same.



De: HTeuMeuLeu ***@***.***>
Enviat el: dimarts, 23 de març de 2021 9:20
Per a: hteumeuleu/caniemail ***@***.***>
A/c: Sergi Juvé Sanchis ***@***.***>; Author ***@***.***>
Tema: Re: [hteumeuleu/caniemail] Oulook.com already supports svg (#142)


Hello, could you be more specific please? SVG image format<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.caniemail.com%2Ffeatures%2Fimage-svg%2F&data=04%7C01%7Csjuve%40laboratorioechevarne.com%7C81d093f7a2974bec864f08d8edd48d2b%7Ccfca949c635045a681a4eddab5412434%7C1%7C0%7C637520844463243645%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZW%2F%2FfNz%2F8qp33vQotHI%2FYfzkhEz6jpzksxx2a5%2B1%2B%2Fk%3D&reserved=0> does work in Outlook.com, but not embedded SVG<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.caniemail.com%2Ffeatures%2Fhtml-svg%2F&data=04%7C01%7Csjuve%40laboratorioechevarne.com%7C81d093f7a2974bec864f08d8edd48d2b%7Ccfca949c635045a681a4eddab5412434%7C1%7C0%7C637520844463243645%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uSVc3XeoksLDPa5TXDbi%2Bd6nMFXmiPoDCBRi9wabh9A%3D&reserved=0>, as stated on Can I email.

**Comment by hteumeuleu** [comment]
The behavior is quite different when using the email client's embed image feature. I believe it converts the image on the fly to a more compatible format (like JPG or PNG). For now, caniemail is purely about rendering possibilities in the inbox, when reading an email, not when replying or forwarding.

I'm closing this for now, but feel free to reopen if you've got any question.
