### ISSUE TITLE
gmail blocks style tags

### ISSUE THREAD

**Issue by michaelwarren1106** [hteumeuleu/caniemail#144]
in desktop gmail, `<style>` tags are definitely being stripped, yet are showing on caniemail as being supported.

What is the way to get style tags in gmail?

**Comment by hteumeuleu** [comment]
There are multiple reasons why a `<style>` tag could be stripped in Gmail desktop webmail:

1. You have too much styles. If you have more than 16Kb of CSS rules, the `<style>` tags that reach this overall limit will be removed.
2. You have unsupported rules. If Gmail sees an `@` within a `@` rule (for example `@media { @font-face { … } }`), it will strip the entire `<style>` tag. 

Feel free to post your code if you want help.

Useful links:

* email-bugs on Gmail: https://github.com/hteumeuleu/email-bugs/issues?q=is%3Aissue+is%3Aopen+label%3AGmail
* Troubleshooting Gmail’s responsive design support : https://www.hteumeuleu.com/2017/troubleshooting-gmail-s-responsive-design-support/

**Comment by michaelwarren1106** [comment]
I tried the literal examples on gmail's own page: https://developers.google.com/gmail/design/css

that claims that style tags work but they were stripped. I was on desktop gmail sending emails to myself. I tried two methods and neither worked.

I tried editing the email content window in dev tools and replacing the contenteditable div with the content in that example page.

I tried downloading a browser extension that claims to send HTML emails and pasted in that example.

In BOTH cases, the HTML was preserved and I got that just fine, but the style tag in the head was stripped.

**Comment by hteumeuleu** [comment]
What are you using to send the email? I'd recommend to use a neutral service like [Parcel](https://useparcel.com/) or [Putsmail](https://putsmail.com/).

**Comment by michaelwarren1106** [comment]
i was just sending to myself using gmail's own compose. didnt want to spin up some tool just to send a test, the email itself sent fine, but everything got stripped that i tried...

**Comment by hteumeuleu** [comment]
Gmail's email composer doesn't support `<style>` tags. Can I email's focus is mostly about displaying HTML emails in the inbox, so I'd say this case is slightly out of scope. But perhaps adding a note on the page stating this could have helped you? (Like “Gmail removes `<style>` tags when replying, forwarding or composing an email.”)

**Comment by michaelwarren1106** [comment]
Ya, I get  that, and it’s a great resource. I was just trying to get to the bottom of why my styles weren’t showing at all.  Was trying to create/test a possible template but didn’t have access to the tool that would be used to send the actual emails themselves. Thanks for the confirmation though! I figured it was better safe than sorry to make an issue
