### ISSUE TITLE
Revisit base64 support in Gmail

### ISSUE THREAD

**Issue by atjn** [hteumeuleu/caniemail#145]
Hi :)

I am no expert on email testing, but as far as I can tell, Gmail does support embedded url base64 images. It doesn't actually load the image directly, but it will host the image on `googleusercontent` and display it from that link instead.

This difference is pretty important, because Gmail is the only major outlier blocking us from using base64 in all emails. It would be great if you could revisit the [base 64 image format table](https://www.caniemail.com/features/image-base64/) and confirm that it is indeed supported. Maybe it would be appropriate to call it `partial support` because it isn't actually reading the base64 images directly.

Thank you in advance!

**Comment by hteumeuleu** [comment]
Hello,

The test code for every feature is available at the bottom of each page in the "_Test it yourself_" section. Here is the one for image formats: https://www.caniemail.com/tests/images.html

The actual code used to test base64 images is the following:

```html
jpg<img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD//gA+Q1JFQVRPUjogZ2QtanBlZyB2MS4wICh1c2luZyBJSkcgSlBFRyB2ODApLCBkZWZhdWx0IHF1YWxpdHkK/9sAQwAIBgYHBgUIBwcHCQkICgwUDQwLCwwZEhMPFB0aHx4dGhwcICQuJyAiLCMcHCg3KSwwMTQ0NB8nOT04MjwuMzQy/9sAQwEJCQkMCwwYDQ0YMiEcITIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy/8AAEQgAKAA8AwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A4qiiprS1mvryG0tozJPM4jRR3JOBXzR8elfQhorent/DdhK1rLLf380ZKvPbOkcW7vtDKxYe/GaxrkQC5k+ymQwZ+QygBse+OM03GxUo8vUiorofDHhtdcmke6uDbWqhlVgMtLLtLBF/AZPoPqK56hxaSb6g4NRUn1CiiikSFdJ4Hhjm8QsZJRCI7O4cSlc7D5TDdj2zn8K5utTw9qMOl6zDcXKu1syvDOqdTG6lGx74bP4VdNpTTZpSaU033J/7T0SKTy49ASa3HHmTXMgmYeuVIQH/AICQPepbnw4smsWkNhKfsV5ALpJpv+WMXO8uRx8pVgcdce9Nk8LT+YWt9R0uaz6rcm9jQY90YhwenGM/WrV94mawmjs9IkhmtIbNLNnnt1dZ8MXY7XBwC7EgHsBV2/nRrZW/eqxa0TUYrvxhp1rZqU0+0jmjt1I5b92252/2mPJ/Adq42uw8M+J5P+EgtvtUekwQ4k3SCwt4sfI2PmCjHOB75xXM31/LqEyyyx20bKu0C3t0hX8QgAJ560ptOKd+r/Qmo04J36v9CrRRRWRgFFFFABRRRQAUUUUAFFFFAH//2Q==">
gif<img src="data:image/gif;base64,R0lGODdhPAAoALMAAACAAP///3+/f7/fv9/v3x+PHz+fP1+vX5/PnwAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAAPAAoAAAE2RDISau9OOvNu/9gKI5kaZ5oqq5s675wLM80JwxEQAxCwSEHmoFAEBiOh0FQgwggZgWn6KB7ygYDUYGQtMIMAV9o8CTLEN6PgCAxxwLLD9jQTreivmRO18MUJ24vYAU4BwWHB0R0FQhZgHYsVIEUCARiEomXAJMtkhkEXlFxdTFUoxVrjxackWEZgwCpq5ArsBiDcxesK1GLF4NNAcLDxMOaKn8YqYfMzYQIzC+Vn7QUu7xSFgKuGte1AQO+Bk2+Gd68A8J70B3nLUflNfLz9PX29/j5+vv8FBEAOw==">
png<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADwAAAAoBAMAAABQlYTMAAAAG1BMVEUAgAD///9/v3+/37/f798fjx8/nz9fr1+fz59QqNX+AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAxElEQVQ4je3OzwuCMBQH8Efp7Coy81hU9w5CHtPox3ES3hXCOhbUfZFQf3ZuswX6PHqq72F82eexPYB/OswkXM1UeyJ6iPLjQraB11Tze3fZNbk/14PboMkZ04Mc4ZduU0B4+CnERdiklm9H4gNjhDCh/i25bsr2AIQth5dnwcBa4yxOg0N8Rlmu1ltKQpiqDcoBjEnFWYqy6Sq+2zK07pH6OxEJElbnotoc0MchFjJmbUycFE4utDHs7dBj7Qwkx25/NG8tKxtX6Jcv2gAAAABJRU5ErkJggg==">
```

I'm wondering if you'd not be referring to using base64 in a Content-ID attachment in an email. If so, Can I email doesn't consider this for the moment.

I just relaunched a test for this in Gmail desktop webmail and confirm that this is still not supported.

**Comment by atjn** [comment]
I ran some more tests on my end, and while I was using the test images supplied by Can i Email, and they were being shown properly in Gmail, it turns out that my Exchange server was converting the base64 images to CID attachments in-transit 🤦‍♂️

Sorry for the inconvenience, and thanks for maintaining this awesome database :)
