### ISSUE TITLE
Typing in the search box is slow in Safari

### ISSUE THREAD

**Issue by stephenreay** [hteumeuleu/caniemail#159]
I haven't dug into what you're doing on keypress events but it's crazy slow to type a search term in Safari on Big Sur (v14.1)

Without looking at the code, my initial suggestion would be to use a setTimeout to delay the actual search action for a fraction of a second, and cancel the previous delayed action whenever a new event occurs, so that typing a term at once just fires off a single action.

**Comment by hteumeuleu** [comment]
Hello! Thank you for your feedback. We’ve just pushed [a fix for this](https://github.com/hteumeuleu/caniemail/commit/a4c47121ff3e6bdca346232e7cbf342d2fba7cc3) by adding a timer as you suggested. Let me know if this is ok on your side too. Thanks!

**Comment by stephenreay** [comment]
Definitely much more responsive!
