### ISSUE TITLE
`width` attribute is not supported in Apple Mail for `<img>`, `width` CSS property works instead

### ISSUE THREAD

**Issue by felixfbecker** [hteumeuleu/caniemail#171]
In Apple Mail (14.0, macOS) using `<img width="300">` to resize a large image to a smaller size doesn't work, instead the image is rendered in full size (spanning the whole window width if not fitting in).

https://www.caniemail.com/features/html-width/ says that it should be supported (at least in 12.4).

Applying inline style `<img style="width: 300px">` works fine however, which is covered in https://www.caniemail.com/features/css-width/.

`style="max-width: 300px"` on the other hand doesn't work either, despite https://www.caniemail.com/features/css-max-width/ saying it should. `max-width` seems to be ignored entirely.

The image I tested is referenced through `cid:` in case that matters. I tested both PNGs and GIFs.

**Comment by hteumeuleu** [comment]
Hey there. Thanks for your feedback. Would you have a full HTML email test reflecting this issue? I feel like this might have to do with auto scaling in emails and not the lack of support for said properties.

**Comment by felixfbecker** [comment]
Sure. Here: [repro.zip](https://github.com/hteumeuleu/caniemail/files/6835066/repro.zip)

![image](https://user-images.githubusercontent.com/10532611/126045123-d87dbbd8-433b-4255-b415-267070793e68.png)

**Comment by hteumeuleu** [comment]
I feel like this might be due to the fact that in your examples, the image is embedded right in the email. If I try the same code with the image hosted online, styles work as expected.

```
<!DOCTYPE html><html><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
    <p>START EMAIL</p>
    <p>This image uses <code>style="max-width: 100px"</code> and should be 100px wide, but is not:</p>
    <img alt="Wallpaper" src="https://i.imgur.com/ILbiWEi.jpg" style="max-width: 100px">
    <p>END EMAIL</p>
</body></html>
```

My guess is Apple Mail has some kind of heuristics to determine whether an image is an attachment and should be displayed as such and thus ignore styles.

**Comment by hteumeuleu** [comment]
I've added a note about this on the `width` feature page. Thanks for your report.
