### ISSUE TITLE
Revisit estimated support calculation

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/caniemail#173]
In light of Apple [Mail Privacy Protection](https://www.macrumors.com/2021/06/10/ios-15-mail-privacy-protection-tracking-pixels/) release later this year, I'd like to revisit how estimated support calculation is done on caniemail. Currently, I'm using emailclientmarketshare.com’s data to match as best as I can email clients on the site. I've always emitted a lot of reservations on the relevance of this ([detailed here](https://www.caniemail.com/support/)) and I think it is a good opportunity to change this.

Let's take the [`<style>` tag](https://www.caniemail.com/features/html-style/) support for example. Currently, it sits at:

- 59.45% Supported
- 17.77% Partially Supported
- 14.09% Mixed Support
- 8.69% Unknown Support

![Screenshot of Estimated Support on caniemail.com](https://user-images.githubusercontent.com/3451753/125965230-0bd65126-61a9-40e9-ad4d-9fd1b5ffdd66.png)

One way to change this would be to give each email client a point, and then calculate the number of support points in total. Using the same example, that'd give us:

- 61.29% Supported (19 clients out of 31)
- 22.58% Partially Supported (7 clients out of 31)
- 16.13% Not Supported (5 clients out of 31)

I like this approach because it seems fair and simple. It gives us the share of **number of email clients that do support that feature** (as opposed to the **market share of email clients that do support that feature**). But it also creates a pretty big misrepresentation of email clients usage, as Gmail (desktop webmail) becomes just as important as Hey (desktop webmail).

I'm curious what any of you think about this?

**Comment by M-J-Robbins** [comment]
Google play store gives rough estimates of installs which could help with weighting of a points system 
For example Gmail has 
Installs 5,000,000,000+
And Outlook has
Installs 500,000,000+

So Gmail on Android is worth 10x more than Outlook on Android


But that is only looking at Android and I'm not aware of something similar for iOS or desktop emails (if anyone know of something please share it).

**Comment by JayOram** [comment]
I think caniemail should be representative of email client support, not necessarily an audience support share. 

The point system above would give the actual CSS support based on the number of clients. 

Maybe with the possibility of choosing which email clients you want to include in the support share?

**Comment by hteumeuleu** [comment]
@M-J-Robbins That's a good idea. But yeah, I think it's going to be very limited as I don't think either that similar data is available on other platforms.

@JayOram Thanks, that's reassuring. There's already an issue filed to make the support share variable depending on the clients you chose (https://github.com/hteumeuleu/caniemail/issues/143). Using a simpler client based share would make this much simpler to code.

**Comment by hteumeuleu** [comment]
I've just pushed [an udpate](https://www.caniemail.com/news/2021-07-26-estimated-support-update/) for this. It was a fun little update to do. I'm closing this issue but let me know if you see anything.
