### ISSUE TITLE
ARIA `role`

### ISSUE THREAD

**Issue by Malvoz** [hteumeuleu/caniemail#179]
Data request for ARIA `role` attribute: https://w3c.github.io/aria/#attr-role

**Comment by Malvoz** [comment]
Already exists: https://www.caniemail.com/features/html-role/, not sure how I missed it.

**Comment by hteumeuleu** [comment]
You might be on to something. `role` doesn't come up if you search for `aria`. I'll fix that.

**Comment by Malvoz** [comment]
@hteumeuleu I believe that should be fixed in https://github.com/hteumeuleu/caniemail/pull/180/.
