### ISSUE TITLE
Improving search results

### ISSUE THREAD

**Issue by Malvoz** [hteumeuleu/caniemail#186]
Search queries can be more forgiving, perhaps by only adding more keywords. A few suggestions:

1. HTML elements should be returned when:
   - wrapped in <q>&lt;</q> and <q>&gt;</q>.
   For example, <q>[&lt;dialog&gt;](https://www.caniemail.com/search/?s=%3Cdialog%3E)</q> should return https://www.caniemail.com/features/html-dialog/.
   - search query ends with <q>element</q>.
   For example, <q>[dialog element](https://www.caniemail.com/search/?s=dialog%20element)</q> should return https://www.caniemail.com/features/html-dialog/.
2. HTML attributes and CSS attribute selectors should be returned when a search query includes <q>attribute</q>.
3. All CSS media query features should be returned on: <q>media query</q>, <q>media queries</q>, <q>media features</q> (<q>media _feature_</q> is a term used by the CSSWG MQ spec, for example `prefers-reduced-motion` is a <q>[User Preference Media Feature](https://drafts.csswg.org/mediaqueries-5/#mf-user-preferences)</q>).
4. <q>html</q> should return all HTML features.
5. <q>css</q> should return all CSS features.

**Comment by hteumeuleu** [comment]
Hey! Forgot to say it there but 8a72958 fixed point number one on your list last month. Also made an update for point number 2 but I'm not sure it matches what you had in mind. (If so, could you clarify with one or more search term examples?) I'll work on number 3 right away. 

As for 4 and 5, I'm not sure that's a desired behavior. Technically, each search makes a request for each result. So a large query like "html" or "css" would likely result in more than a hundred requests (for that single query). I'd rather invite people to browser the [Features index page](https://www.caniemail.com/features/).

**Comment by Malvoz** [comment]
@hteumeuleu I'm happy with the improvements, thanks!
