### ISSUE TITLE
`letter-spacing` partial support in Outlook (additional issue)

### ISSUE THREAD

**Issue by alicemeichi** [hteumeuleu/caniemail#192]
Found that the partial support in Outlook extends to more than just negative values, but also to values with `em` units.

How it should render (Apple Mail): (5x text = 0.4em letter-spacing, 3x text = 0.2em letter-spacing)
![image](https://user-images.githubusercontent.com/10135143/135202962-0f02f1aa-2b48-415d-a777-61ccdcc49843.png)

How it renders in Outlook: (5x text = 0.4em letter-spacing, 3x text = 0.2em letter-spacing)
![image](https://user-images.githubusercontent.com/10135143/135202996-588b110d-c797-4f99-9a1c-2d8f871c934d.png)

**Comment by hteumeuleu** [comment]
Nice catch. I do see the difference but I'm not sure how to explain it. It looks like [in Word](https://support.microsoft.com/en-us/office/change-the-spaces-between-text-e9b96011-1c42-45c0-ad8f-e8a6e4a33462), letter-spacing is defined with an option "Expanded" or "Condensed" by `x` pt. It'd be interesting to know how this is represented when you export a Word document for the web.

I'll add a note about this in the letter-spacing page. Thanks for your report, Alice!
