### ISSUE TITLE
Gmail web versions

### ISSUE THREAD

**Issue by husseinalhammad** [hteumeuleu/caniemail#201]
As far as I know Gmail has the following distinct webmail versions:

- Desktop standard view
- [Desktop basic HTML view](https://support.google.com/mail/answer/15049?hl=en)
- Mobile standard view
- Mobile "older version": the option is listed in the footer of the mobile standard view. I guess this counts as the mobile basic view? 

On caniemail there's Desktop Webmail and Mobile Webmail. These are the desktop standrad view and the mobile standard view. 

The mobile "older version" seems to support plain text only so it's probably not relevant here. However, the desktop basic HTML view supports HTML emails, but is different from desktop/mobile standard views*. I'm unsure whether it's worth adding to caniemail as a separate client.

---

*I was under the impression that the desktop basic view and the mobile standard view handle HTML in the same way, but I recently noticed the `height` CSS property is transformed to `min-height` on the desktop basic view, but not on the mobile standard view.

**Comment by hteumeuleu** [comment]
Thanks for reporting this. My feeling is that since these versions of Gmail are "older" versions, they're not wildly used and there's not much interest for this kind of data. [Am I wrong here?](https://knowyourmeme.com/memes/am-i-out-of-touch) What would be a good use case to defend adding this?

**Comment by husseinalhammad** [comment]
## Mobile "older version"
I don't think this needs to be added. From what I see it displays emails in text only.

## Desktop basic HTML view
I do not view this as an older version of Gmail, but a supported version for older browsers. While we don't have data, if I have to guess I would say it is more widely used (globally) than Hey for instance. And it is actually a supported version of Gmail, unlike Outlook 2007 which has been officially retired.

I think there are types of people who would use this version such as:

1- People who need to use older browsers
2- People who need to use less data (they use modern browsers, but want to use less data)

I am yet to encounter a single person who uses the standard mobile version (which is already listed on caniemail), but I encountered people who fall under (1) or (2).

When it comes to (1), from personal experience:

- Some enterprise software still requires IE. I saw this first hand. While Edge has an IE mode now, I'm not sure the average person knows how to enable this (from my experience: they don't). This doesn't mean Gmail is used on IE in this case, but IE is certainly still used by some.
- To this day I see old small businesses still use Windows XP or Vista and IE. And they do use Gmail.

It may not be relevant to a lot caniemail users, and I am with the approach of not doing more work unless it is needed. And from a business perspective, a lot of companies may not care about this. But I can see how this can be relevant to government departments who send email communications as they are obligated to ensure what they send is accessible to as many people as reasonably possible.

**Comment by hteumeuleu** [comment]
Google as announced phasing out Gmail Basic View in february 2024, so I feel this issue is no longer relevant.
