### ISSUE TITLE
Can I Email "font-stretch" CSS Property?

### ISSUE THREAD

**Issue by alexander-lysenko** [hteumeuleu/caniemail#210]
https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch
By the way, it is supported by modern browsers (https://caniuse.com/?search=font-stretch)

**Comment by o-t-w** [comment]
This might be impossible to test as a CSS property because many clients don't support custom fonts. Some system fonts (e.g. on iOS and Mac) do support expanded and condensed versions. On Android and Windows I don't think any do.
