### ISSUE TITLE
Vmail tool to check HTML and CSS for templates based on Caniemail data

### ISSUE THREAD

**Issue by le0pard** [hteumeuleu/caniemail#214]
It is not an issue, it is more like thanks for your work and data in JSON format. 

I made tool with WASM module (no server), which check HTML and CSS from email templates and based on Caniemail data and show report. Links from each result also point to caniemail. Thanks for your work, I hope this tool also will be useful.

https://github.com/le0pard/vmail

**Comment by hteumeuleu** [comment]
Hey thanks, that's pretty neat! I'm thinking about publishing a list of tools that use Can I email's data somewhere, somehow, akin to caniuse’s Third Party Tools list. I'll create a dedicated issue for close this one. Thank you!

**Comment by hteumeuleu** [comment]
Here’s the followup thread: #215 
Thanks again for your message. I'm closing this issue now.
