### ISSUE TITLE
Add the img tag to the dataset

### ISSUE THREAD

**Issue by DiedeGu** [hteumeuleu/caniemail#217]
Dear CanIemail, 

I couldn't find the `<img>` tag in the dataset, the the newer `<picture>` has been checked as well as the `loading`  `<img>` attribute but not the `<img>` tag itself, and I was curious about its support. If there is a way to easily check for this and add the result to the dataset myself please let me know. 

Kind Regards,

**Comment by hteumeuleu** [comment]
Good idea! I'd assume it'd be pretty much 100%. But it could be a good opportunity to add notes about which email clients block images by default.

**Comment by hteumeuleu** [comment]
Added this month: https://www.caniemail.com/features/html-img/
