### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by Roye7777777** [hteumeuleu/caniemail#218]
Outline is perhaps an interesting feature to be added. 
It can sometimes be useful in dark mode, albeit in a limited way. For instance, in Gmail on iOS, one can state an outline to be white and the colour specified will not be inverted in dark mode, while in Gmail on Android, the colour is still being inverted.

**Comment by hteumeuleu** [comment]
There you go: https://www.caniemail.com/features/css-outline/ !
