### ISSUE TITLE
Can I email `<abbr>` and `<dfn>` tags?

### ISSUE THREAD

**Issue by genericusername3** [hteumeuleu/caniemail#222]
Hi, I could find neither the [`<abbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr) nor the [`<dfn>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn) tag in the dataset, should they be added?

To be quite honest, they don't do a lot (`abbr` just adds a dotted underline and a different cursor as well as reportedly small caps in some browsers, `dfn` uses italics). I could definitely just use styled `span` elements instead, but I thought “Hey, let's do extra work and open an issue for that”.

I would expect support to be quite good across clients (since [even IE 7 supports `abbr`](https://caniuse.com/mdn-html_elements_abbr) and [at least IE 11 supports `dfn`](https://caniuse.com/mdn-html_elements_dfn)), but I'm really not sure. This is why I think it'd be good to add the two to caniemail as well.

**Comment by husseinalhammad** [comment]
> To be quite honest, they don't do a lot

They are elements with semantic meaning. That's makes them significant enough to add!

**Comment by hteumeuleu** [comment]
These were added last september:

* https://www.caniemail.com/features/html-abbr/
* https://www.caniemail.com/features/html-dfn/
