### ISSUE TITLE
word-break in Yahoo/Aol has a workaround

### ISSUE THREAD

**Issue by jkupczak** [hteumeuleu/caniemail#242]
As discovered by @M-J-Robbins here https://github.com/hteumeuleu/email-bugs/issues/115#issuecomment-1158751044, there are workarounds for using word-break. Unsure if it's the same for Aol and Yahoo.

**Comment by hteumeuleu** [comment]
Is this a workaround though? If I understand correctly, Mark’s comment points to a way to avoid Yahoo’s default styles on td (which do apply a `word-break`). But this doesn't let you set your own `work-break` from within an HTML email. 

I'm closing this but feel free to comment or reopen if you feel we got something wrong.
