### ISSUE TITLE
position: absolute

### ISSUE THREAD

**Issue by collinanderson** [hteumeuleu/caniemail#26]
I want to do a layout like this, but `position: absolute` (and `position: relative`) doesn't seem to work in gmail, so it would be nice to know where that works.

![image](https://user-images.githubusercontent.com/129234/64883692-96951f00-d625-11e9-8ef7-a36353e8fda1.png)

**Comment by hteumeuleu** [comment]
There you go: https://www.caniemail.com/news/2021-05-16-css-position/
