### ISSUE TITLE
image quirks

### ISSUE THREAD

**Issue by collinanderson** [hteumeuleu/caniemail#27]
I tried sending an email with an 3mb externally-hosted animated gif, but it didn't work on Outlook for desktop. So I'm guessing it was either blocking the externally hosted image, or it didn't like the animated gif, or it didn't like that it was 3mb.

**Comment by hteumeuleu** [comment]
Could you provide the code example and the image you tested with?

**Comment by evaryont** [comment]
I've actually ran into this before: Outlook on Windows (not sure about MacOS) does not support animating GIFs. It will pull the first frame of the image and not show any more. On Android, Outlook _does_ render the full animation. I think it might be tied to desktop Outlook's rendering engine.

**Comment by hteumeuleu** [comment]
We've [added image format data a few months ago](https://www.caniemail.com/news/2020-02-07-two-great-contributions/), including [specific notes for animated gifs](https://www.caniemail.com/features/image-gif/).

I'm closing this issue for now as there's not much more I can do without more detailed examples. Feel free to reopen if you have more informations.

**Comment by collinanderson** [comment]
https://www.caniemail.com/features/image-gif/ is perfect. Thanks! (And, yes it was an animated gif that was the issue.)
