### ISSUE TITLE
AMP tag support

### ISSUE THREAD

**Issue by ianmobbs** [hteumeuleu/caniemail#28]
As the `amp` project rolls out more tags that are supported by Gmail, it would be great to see if those tags are supported by other email clients as well - `<amp-form>`, for example ([link](https://amp.dev/documentation/components/amp-form/)).

**Comment by adamzr** [comment]
Or just know which clients support AMP emails at all

**Comment by yannicka** [comment]
AMP is not a standard and I think that it is a very bad technology, so I think it is better not to add it to avoid promoting it.

**Comment by niutech** [comment]
@yannicka I disagree. AMP for Email support should be included for informational purposes, not advertising.

AMP for Email is supported by at least: Gmail, Yahoo Mail, Outlook.com, Mail.ru, Litmus, SendGrid and SparkPost.

**Comment by ianmobbs** [comment]
Whoops - accident 😅

**Comment by ianmobbs** [comment]
@yannicka Regardless of anyone's opinion on whether it _should_ be a standard, it's quickly becoming one. As such, I agree with @niutech - it's being used more and more often by email senders and supported more and more often by email clients, and as such, should be included in this project, purely for data purposes.

**Comment by hteumeuleu** [comment]
Hello there! As far as I understand, AMP for email clients all support the same levels of AMP components (https://amp.dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format/?format=email). AMP for email is listed here (https://www.caniemail.com/features/amp/). Feel free to reopen the issue if you feel this doesn't match your expectations. Thanks for submitting this issue.
