### ISSUE TITLE
Issues with Gemfile.lock

### ISSUE THREAD

**Issue by L1Q** [hteumeuleu/caniemail#280]
## Context
I am running Manjaro Linux.
Tried following [Installation](https://github.com/hteumeuleu/caniemail#installation) instructions today but failed hard on the ``bundle install`` step without any helpful error information.
<details>
  <summary>Example of the errors I was getting</summary>

![image](https://user-images.githubusercontent.com/6942070/191879829-86fdb3fd-6555-42f5-aa05-61600a159aec.png)
</details>

## The issue
After some time troubleshooting, I figured out the culprit: ``Gemfile.lock``.

This [SO answer](https://stackoverflow.com/a/6366523/) suggests issues like this can happen due to platform differences.
> My workmates and I have different Gemfile.lock, because we use different platforms, windows and mac, and our server is linux.

When it's not present in the git repository, the ``bundle install`` command always generates fresh ``.lock`` with all the dependencies correctly resolved.

## Ad hoc solution
If anyone else ends up having this problem, just delete the ``Gemfile.lock`` locally after cloning the repository and run ``bundler install`` again, it should work like a charm.

### Radical
Just remove ``Gemfile.lock`` from the repository for good by adding it to ``.gitignore``

### Simple
Acknowledge the issue in the installation instructions like this:

> **Note**
> in case ``bundle install`` fails, try deleting ``Gemfile.lock``.

**Comment by husseinalhammad** [comment]
If the lock file is needed for deployment, then I think it needs to stay.

> in case bundle install fails, try deleting Gemfile.lock

This means the contributor must know not to commit their version of `Gemfile.lock` - which too is not ideal.

Would using WSL on Windows solve the install fail issue? If so, that can be documented in the installation guide.

**Comment by L1Q** [comment]
> This means the contributor must know not to commit their version of `Gemfile.lock` - which too is not ideal.

That's true.

> Would using WSL on Windows solve the install fail issue? If so, that can be documented in the installation guide.

Clean installed WSL2 Ubuntu (``wsl --install``), updated it and installed [Jekyll using these steps](https://jekyllrb.com/docs/installation/ubuntu/)
**All went fine, no issues with caniemail in that configuration.**

The Ruby version I get in the WSL2 Ubunu is
```ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]```
whereas the ruby version on my Manjaro Linux is
```ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]```

Currently looking for any other differences.

**Comment by L1Q** [comment]
> If the lock file is needed for deployment, then I think it needs to stay.

I don't believe it is needed, here is an [example](https://github.com/ShareX/sharex.github.io) of a Jekyll website with ``Gemfile.lock`` in ``.gitignore`` for 6 years now.

**Comment by hteumeuleu** [comment]
Honestly, I know so little about this that I'm fully trusting @L1Q on this! I'll push an update to remove it and we’ll see if anyone complains. Thanks for bringing this up!
