### ISSUE TITLE
inline-block

### ISSUE THREAD

**Issue by davc93** [hteumeuleu/caniemail#288]
inline-block property doesn't appear in search bar.

![2022-10-24 (2)](https://user-images.githubusercontent.com/80164430/197570790-b689b076-4d02-42c8-86fd-0850575a19e3.png)

**Comment by husseinalhammad** [comment]
@hteumeuleu Should the search return CSS properties when searched by values in general? 

If so:

- searching by `inline-block`, properties like `display` would be returned (what @davc93 is expecting here)
- searching by `left`, properties like `text-align` and `float` would be returned
- and so on...

**Comment by hteumeuleu** [comment]
@husseinalhammad I'd say it should. This is just a matter of missing keywords.
