### ISSUE TITLE
Can I email: Support for Base 64 image format

### ISSUE THREAD

**Issue by dalaranunion** [hteumeuleu/caniemail#289]
I was trying to add an image via Base64 and I ran into the Can I email. The Gmail: MacOs (iOs) and Android are marked as not supported however it does 

I run a test using - [this link](https://www.caniemail.com/tests/images.html).

My test: 
- simply selected text and images
- copied and pasted them on Outlook (on MacOS)
-  send the email over to a colleague 
- View the same email on:
- - MacOS  Apple Mail App (gmail)
- - Android Gmail App
- - Gmail Web with Firefox Android (v106.1.0)
- - Gmail Web with Firefox MacOS (106.0.3 64-bit)

Might be able to test this on windows email client too

**Comment by hteumeuleu** [comment]
I've retested just right now, using the sample email from caniemail and Parcel to send the email, and can confirm that no Base64 images are shown on Gmail (neither desktop webmail, iOS or Android). My guess is that there is a flaw in your process of testing when doing this:

> simply selected text and images
> copied and pasted them on Outlook (on MacOS)

I suppose that when doing this, Outlook on macOS embeds the images as CID embedded images. So they're no longer inline base 64 images. Feel free to reopen if you find another way of testing this.
