### ISSUE TITLE
Generalize e-mail client features

### ISSUE THREAD

**Issue by ghost** [hteumeuleu/caniemail#29]
​

**Comment by kdex** [comment]
(For reference, "PGP and S/MIME support" is also discussed in #24).

**Comment by hteumeuleu** [comment]
I like the general idea, and it's already been request (#24 and #23 as you mentioned). However, our focus for now is really on HTML and CSS features. But out of curiosity, what change would be required in the data model to get these features tracked?

**Comment by kdex** [comment]
Upon closer inspection, it looks like the models could indeed store such data with only minimal change required. If you want, I could transform each bullet point that hasn't been requested yet into its own issue, so that we can close this.

**Comment by hteumeuleu** [comment]
As this is not something I'll look into anytime soon, I think it's ok to keep your issue as it is right now. Thank you!

**Comment by hteumeuleu** [comment]
Closing this as user was deleted and the first issue no longer is available.
