### ISSUE TITLE
Yahoo AMP support 

### ISSUE THREAD

**Issue by o-t-w** [hteumeuleu/caniemail#297]
[Yahoo claims ](https://senders.yahooinc.com/amp/) “AMP for Email is currently supported on Yahoo and AOL Webmail as well as the Yahoo Mail applications on iOS and Android.”
I haven’t manually tested this but I assume this is accurate. This is not reflected in the data shown on caniemail, which shows no AOL support and shows Yahoo as only supporting webmail.

**Comment by hteumeuleu** [comment]
I have never seen an amp email work in Yahoo clients despite Yahoo’s claims. (I just tried again with a Google Docs notification, which has an amp version working fine in Gmail, but not showing in Yahoo — even desktop webmail). Maybe this is because Google isn't safelisted in Yahoo? I'd love to be able to test this to update the data.

**Comment by husseinalhammad** [comment]
It is indeed supported on Yahoo. There's no obvious way to send AMP tests to a Yahoo address like Gmail though.

Sign up with a Yahoo email address to the newsletter form at the bottom (with the heading "Get a series of emails with different games in them") and you'll get a series of AMP emails that work on Yahoo:
https://stripo.email/guide-to-email-gamification/ebook/

Note that non-Yahoo addresses that are connected to your Yahoo account won't render the AMP emails.

**Comment by hteumeuleu** [comment]
@husseinalhammad Thanks! I just tried but apparently Strip's emails no longer validate and thus they don't show their amp versions (even in Gmail). 

[![Screenshot of Stripo's amp email code showing a validation error.](https://i.imgur.com/vAauHlDm.png)](https://i.imgur.com/vAauHlD.png)

I'll trust you both on this and update to reflect support in Yahoo anyway.
