### ISSUE TITLE
CSS backdrop-filter

### ISSUE THREAD

**Issue by o-t-w** [hteumeuleu/caniemail#302]
CSS [backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) let's you apply visual effects (e.g. blur) to everything behind an element.

**Comment by snippsysnappsy** [comment]
Sorry if it's not kosher, but as I too was looking for this, I found this:
https://www.campaignmonitor.com/css/filters/backdrop-filter/

According to this, it's only possible with AOL, Apple 10 Mail, Outlook for Mac, iOS 10 Mail, iOS 11 Mail. All Apple with -webkit prefix.

**Comment by strawberry3269** [comment]
您的邮件已收到， ~~~

**Comment by hteumeuleu** [comment]
Fixed with #381
