### ISSUE TITLE
Apple Mail data on comparison chart is wrong, is different than data on property pages

### ISSUE THREAD

**Issue by jensimmons** [hteumeuleu/caniemail#329]
When I look at the comparison chart for Apple Mail on iOS and macOS, I see several properties that are supported in Mail on one platform, but not the other. But then when I click on many of those property names to see the pages for the properties, I see that in fact, they are fully supported on both macOS and iOS. Which matches what I know to be true. 

Something is wrong with the comparison chart and where it's getting its data from. 

To reproduce: 
1. Go to https://www.caniemail.com/clients/
2. Check "Apple Mail", to compare Apple Mail on macOS to Apple Mail on iOS.
3. Scroll down to the mixed support section. You'll see:
<img width="1286" alt="Screenshot 2023-03-08 at 4 15 18 PM" src="https://user-images.githubusercontent.com/108474/223851748-ffff0128-9c3f-4594-9240-bc1c4cda44f7.png">

The data is wrong for:
- [@media (orientation)](https://www.caniemail.com/features/css-at-media-orientation/)
- [border-inline & border-block individual logical properties](https://www.caniemail.com/features/css-border-inline-block-individual/)
- [border-inline & border-block](https://www.caniemail.com/features/css-border-inline-block/)
- [border-radius logical properties](https://www.caniemail.com/features/css-border-radius-logical/)
- [margin-block-start & margin-block-end](https://www.caniemail.com/features/css-margin-block-start-end/)
- [margin-inline & margin-block](https://www.caniemail.com/features/css-margin-inline-block/)
- [margin-inline-start & margin-inline-end](https://www.caniemail.com/features/css-margin-inline-start-end/)
- [margin-inline & margin-block](https://www.caniemail.com/features/css-margin-inline/)
- [padding-block-start & padding-block-end](https://www.caniemail.com/features/css-padding-block-start-end/)
- [padding-inline & padding-block](https://www.caniemail.com/features/css-padding-inline-block/)
- [padding-inline-start & padding-inline-end](https://www.caniemail.com/features/css-padding-inline-start-end/)

All of these are supported on both macOS and iOS — your own data says so. Click the name of the properties to see the correct data.

**Comment by hteumeuleu** [comment]
Thank you for reporting this bug. There is indeed an issue when comparing data with mixed results. The problem comes from the JSON formatted data where support data is represented as an object: `{"10.3":"n","12":"y","13":"y","15":"y"}`. But once interpreted in JavaScript, the values for this object get sorted in a different order and this is why the first value here (`"10.3":"n"`) is sorted last and is the one used in the comparison. 

The fix is not trivial as it may require a change in the JSON format (that is also used by third parties). I'll see how I can get this sorted properly.

**Comment by hteumeuleu** [comment]
I just pushed a fix for this. Sorry this took so long! Thanks again for reporting this @jensimmons and feel free to let me know if you see anything else.

**Comment by jensimmons** [comment]
Thank you!!
