### ISSUE TITLE
Background CSS attribute Notes footnote numbers don't line up with data

### ISSUE THREAD

**Issue by pinksharpii** [hteumeuleu/caniemail#346]
Just looking at the Background item, and there are 7 Notes under it. But in the actual data the numbers only ever go to 6. It looks like number 7 is in regards to Gmail. But the one Gmail client that has a footnote has a 6 on it. I'm thinking the data got updated at some point but maybe the notes never did change to reflect that?

<img width="1370" alt="Screen Shot 2023-07-25 at 9 33 21 AM" src="https://github.com/hteumeuleu/caniemail/assets/3431241/3a5a7493-6922-4acc-ac79-464f1b36bc9b">

**Comment by strawberry3269** [comment]
您的邮件已收到， ~~~

**Comment by hteumeuleu** [comment]
Oops! Gmail (desktop webmail) should indeed have both notes 6 and 7. Fixed it. Thanks for reporting it!
