### ISSUE TITLE
max-width property

### ISSUE THREAD

**Issue by mineges** [hteumeuleu/caniemail#348]
"max-width" property has incorrect legend colours for Apple Mail iOS 5.1 and 6.1, as well as Outlook Windows 2019 + Windows Mail 2020-01. There should be yellow "partial support" legend colours (based on their assigned notes).

**Comment by strawberry3269** [comment]
您的邮件已收到， ~~~

**Comment by hteumeuleu** [comment]
Thanks, great point indeed! Fixed it now.
