### ISSUE TITLE
Add custom Open Graph metas for features

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/caniemail#35]
Currently, when the site is shared across social networks, the sites will display the content inside the page's [Open Graph](https://ogp.me/) metas. 

![Screenshot of sharing a link from caniemail.com in Facebook](https://user-images.githubusercontent.com/3451753/65037317-af674280-d94d-11e9-9971-0aac964ff5a9.png)

It would be great to be able to have custom open graph metas for every feature. This sounds easily doable for the `og:title` of the page, in order to have for example `Can I email… <video> element` (instead of just `Can I email…`).

But then I'm thinking the `og:description` and `og:image` could reflect the support of the actual property for the 4 main families (Apple Mail, Gmail, Outlook, other clients). Something like:

```
Supported in Apple Mail. Not supported in Gmail. Partially supported in Outlook and other email clients.
```

The screenshot could also reflect the data. By having 256 pre-rendered images, we could get the correct image for the correct support summary (like `yyyy.png`, `yyyn.png`, …). Here's what the final result could look like:

![Screenshot of sharing a link from caniemail.com in Facebook after the few tweaks mentioned here](https://user-images.githubusercontent.com/3451753/65038184-b1ca9c00-d94f-11e9-9a54-61c73017002e.png)

**Comment by WhiteHotLoveTiger** [comment]
What's the different between **Red Not supported** and **Orange Not Supported** ?

As someone not super familiar with the site, seeing this preview on twitter would make me a little confused. Is it possible to merge these two states into one, at least for the OG images? It would cut the permutations down to 81 images I think.

**Comment by hteumeuleu** [comment]
Actually, my little preview image up here is wrong. The orange ones should read "Partially supported".

**Comment by hteumeuleu** [comment]
I've added dynamic text for both `<meta name="description">` and `<meta name="og:description">`. You can now get a text summary for the first four most popular client families without even coming to the site.

![Screenshot of a page shared on Slack](https://user-images.githubusercontent.com/3451753/65595739-ad2c6600-df95-11e9-9968-8494905b2db4.png)

**Comment by hteumeuleu** [comment]
I'm closing this for now. This is good enough as it is now for me.
