### ISSUE TITLE
text-wrap: pretty and text-wrap: balance

### ISSUE THREAD

**Issue by o-t-w** [hteumeuleu/caniemail#362]
Now that these properties are making their way to browsers it would be nice to document them.

[text-wrap: pretty](https://chromestatus.com/feature/5145771917180928?context=myfeatures)
[text-wrap: balance](https://developer.chrome.com/blog/css-text-wrap-balance/)

**Comment by DCoder18** [comment]
This has been added now.
https://www.caniemail.com/search/?s=text-wrap
