### ISSUE TITLE
CSS box-shadow in Outlook

### ISSUE THREAD

**Issue by graymatter00** [hteumeuleu/caniemail#374]
**Can I Email** states that the CSS `box-shadow` property is not supported all **Outlook** mail clients except for macOS.

See https://www.caniemail.com/search/?s=box-shadow

However, my testing shows `box-shadow` now working in **Outlook.com**, **Outlook for Android** and in **Outlook (new) for Windows**.

**Comment by hteumeuleu** [comment]
You're right, I'll update this.

**Comment by graymatter00** [comment]
@hteumeuleu Thanks for updating it. However, you didn't update the entry for **Outlook for Windows**.  The latest version, **Microsoft Outlook Version 1.2023.1204.100 (Production)**, also supports `box-shadow`.

**Comment by hteumeuleu** [comment]
Yes, because I haven't been able to test it on the "new" Outlook for now. I plan to do a big batch of retests for it next month so it'll be part of that update.
