### ISSUE TITLE
CSS Nesting is supported in Apple Mail

### ISSUE THREAD

**Issue by jensimmons** [hteumeuleu/caniemail#392]
You show CSS Nesting as only partially supported in Apple Mail. There are two things a bit off about this data.

1) Full support shipped in Safari 17.2. (iOS 17.2, macOS 14.2)
https://webkit.org/blog/14787/webkit-features-in-safari-17-2/#css
https://caniuse.com/css-nesting

2) The note for partial support says it was buggy. 
> Buggy. E { F {}} doesn’t work, but E { & F {}} does.

This notes gives the impression that the implementation was incorrect. But actually, at the time, that's exactly what the CSS Nesting web standard called for. Element selectors (like `div` or `h1`) required an `&` to come before them.

It was only later that the CSS Working Group figured out how to relax this requirement, and so WebKit and Chromium were updated to the later version of the standard.

It makes sense to note this for developers. You can see how Can I Use did so. But calling it "buggy" gives the impression they cannot trust the implementation, which is not correct. They should trust it. Just know that for a brief period, it had this limitation.

**Comment by hteumeuleu** [comment]
Thank you for taking the time to explain this. (I didn't know that!) I've updated the page to replace "buggy" with "partial" and add the updated data.

**Comment by jensimmons** [comment]
It looks like iOS was updated, but not macOS. Both should have been changed at the same time — in iOS 17.2 and macOS 14.2.

<img width="286" alt="Screenshot 2024-01-31 at 6 27 53 PM" src="https://github.com/hteumeuleu/caniemail/assets/108474/eedcd67b-e7d5-4b89-9c3f-40add248b6ec">
