### ISSUE TITLE
HEIF image format is supported in Apple Mail

### ISSUE THREAD

**Issue by jensimmons** [hteumeuleu/caniemail#393]
WebKit added support for HEIF image format when shipping Safari 17.0, iOS 17 and macOS Sonoma (14).
https://webkit.org/blog/14445/webkit-features-in-safari-17-0/

**Comment by jensimmons** [comment]
I'm seeing the same results in Apple Mail as I am in Safari.

<img width="1554" alt="Screenshot 2024-01-29 at 9 07 52 PM" src="https://github.com/hteumeuleu/caniemail/assets/108474/27e70f2a-1f94-490d-94d5-dd7dd59d7819">

**Comment by hteumeuleu** [comment]
Thanks! I've updated the data for this.
