### ISSUE TITLE
Remove the PPM image format page

### ISSUE THREAD

**Issue by michael-westphal** [hteumeuleu/caniemail#396]
This issue is meant to start a discussion on the merits of continuing to include a page for the [PPM image format](https://www.caniemail.com/features/image-ppm/).

PPM is an archaic image format that isn't supported by any modern browser or email client. MDN and Can I Use make no reference to it, either. I'd argue that continuing to include a page for it is doing more harm than good. Support is at 0% and, in all likelihood, will never improve. It's confusing for users who have never heard of it, and it gives the impression that the email world is actually asking that email clients support this format, which, in my experience, isn't the case.

What do others think? @M-J-Robbins I know you created this page in the first place, so I'm particularly interested in your opinion.

**Comment by M-J-Robbins** [comment]
I think I included it in my early test as I was looking into every image format I could find at that time. Thinking maybe that an archaic email client like windows Outlook might support an archaic image. 

Personally I don't mind either way. Happy to keep it up, happy to remove it. 

For me i see CanIEmail as reporting on feature support and not asking for feature support so i don't see that as an issue myself, however if that's a thought you've had maybe other have that thought too so it could be an issue.

**Comment by hteumeuleu** [comment]
Honestly, I'm up for removing it as well. It's nice to test things like this in case they work and open new doors. But in this case, it doesn't. Also, it's not like this was a popular image format or practice at any point in time.
