### ISSUE TITLE
<style> tags in Gmail mobile webmail seem to work

### ISSUE THREAD

**Issue by eckstein** [hteumeuleu/caniemail#397]
I'm currently in the middle of a deep-dive template refactor and from my testing, it seems to me that `<style>` tags are working just fine in Gmail mobile webmail, despite the caniemail table indicating otherwise. I'm on an Android S23 and I've tested on a personal Gmail account as well as a work account (non-@gmail account).

I've also confirmed what another poster said a few days ago that `<style>` tags work in Gmail `<body>` tags (webmail, mobile, android at least) if they are wrapped with a `<head>` element nested in the body.

**Comment by michael-westphal** [comment]
I've tested on several devices and `<style>` tags are still not working for me. I wonder if Google is slow-rolling a release. I'm seeing `CLIENT_BUILD_LABEL: apps-mobile-ui_832.1` in the DOM. @eckstein what value are you getting?

**Comment by eckstein** [comment]
So sorry, it was a false positive. The inlining tool got turned on in my Iterable Sandbox instance so my test previews were all looking just so sharp on gmail mobile web when they shouldn't have!

I was hopeful because it's 2/1, the dreaded day of inbox changes from Gmail/Yahoo and I thought maybe they'd rolled out some new stuff.

Alas, I'm just an idiot instead. Sorry!

**Comment by hteumeuleu** [comment]
That happens, nothing idiot here! Thanks for warning us here anyway!
