### ISSUE TITLE
View feature support by email client - for a user-specifiable group of clients

### ISSUE THREAD

**Issue by jonosheehy** [hteumeuleu/caniemail#40]
If, for example, I know that 90% of my audience use email clients A, B, C, D and E, then it would be great to be able to specify those 5 clients, and then see:

- Which features are supported by _all_ specified clients
- Which features have questionable support across the specified clients

**Comment by hteumeuleu** [comment]
This is now possible via the comparison feature on the clients page : https://www.caniemail.com/clients/

Feel free to reopen and let me know if you need anything else.
