### ISSUE TITLE
I got the blend-mode trick to work on Gmail App (non-@gmail) iOS 17.3

### ISSUE THREAD

**Issue by eckstein** [hteumeuleu/caniemail#402]
I haven't tested on anything but iOS 17.3, but I was able to get the blend-mode trick to work on different text colors and backgrounds on Gmail App iOS with a non-gmail address.

I added this to **both** the `<head>` and `<body>` section
```
<style type="text/css">
            u + .body .gmail-blend-screen.white-on-black { background:#000000; mix-blend-mode:screen; }
            u + .body .gmail-blend-difference.white-on-black { background:#000000; mix-blend-mode:difference; }

            u + .body .gmail-blend-screen.black-on-white { background:#FFFFFF; mix-blend-mode:screen; }
            u + .body .gmail-blend-difference.black-on-white { background:#FFFFFF; mix-blend-mode:difference; }

            u + .body .gmail-blend-screen.black-on-grey { background:#F4F4F4; mix-blend-mode:screen; }
            u + .body .gmail-blend-difference.black-on-grey { background:#F4F4F4; mix-blend-mode:difference; }
        </style>
```

And then I did something like this in my various sections depending on the colors I needed:

```
<div class="id-plain-text wrapper" style="background-color: #000000; background-image: linear-gradient(#000000,#000000);  padding:10px 20px;">
        <div class="id-plain-text"
            style="background:transparent;margin: 0 auto; max-width: 600px;font-size: 18px; text-align:left;">
            <div class="gmail-blend-screen white-on-black">
            <div class="gmail-blend-difference white-on-black">
<p><span style="color: #ffffff">Content here</p>
        </div>
        </div>
        </div>
    </div>
```

From what I can tell on the caniemail table, `<style>` tags shouldn't work in Gmail app iOS for non-Gmail accounts, but this seems to. I'm going to do some more experimenting after the long weekend, but wondering if anyone else has seen these or used it?

_ps. I verified my css inlining tool wasn't active, which has caused me false-positives before of course._

**Comment by husseinalhammad** [comment]
I think the blend mode hack bit is not significant here. This issue just discusses whether `<style>` is supported on the Gmail app with a non-Google account.

## non-Google account
I think the note on https://www.caniemail.com/features/html-style/ is not correct. It should read "non-Google" account, not "non-Gmail account". A Google account can have a custom domain (e.g. a Google Workplace user) - it could be unicorn@example.com and still be a Google account.

Can you confirm whether the account you tested on is not a Google account?

## Test
Testing the reduced test case from this repository (https://github.com/hteumeuleu/caniemail/blob/master/tests/html-style.html) I don't see it working on Gmail Android. Can you run this test and share your results?

**Comment by eckstein** [comment]
You're right, the blend hack trick was just an example. However, the grid also says that it's not supported in iOS on non-gmail accounts, yet it works, so it's a little bit related.

I always thought that "non-gmail" account meant Google Workspace or any other email not ending in @gmail (except for imap). The email I tested on was a Google Workspace, non-gmail account.

If that's not the case, then yeah, a language update may be in order on the grid.

**Comment by eckstein** [comment]
Unfortunately I don't access to the iDevice I was using to test again until after the weekend, but happy to test after that. Litmus/Emailonacid don't cover this inbox well.
