### ISSUE TITLE
Margins

### ISSUE THREAD

**Issue by joeyre** [hteumeuleu/caniemail#42]
Margins require some attention in HTML email as they react quite differently in Outlook (of course), would be useful to have this included!

**Comment by bradenaa** [comment]
Also - in Gmail you can not use negative margins. Perhaps its the same in Outlook

**Comment by hteumeuleu** [comment]
There you go: https://www.caniemail.com/features/css-margin/

I didn't test the individual `margin-left`, `margin-right`, `margin-top`, `margin-bottom` properties. But I feel like support would be identical.
