### ISSUE TITLE
box-shadow support on iOS phone

### ISSUE THREAD

**Issue by hithamalbasheir** [hteumeuleu/caniemail#438]
I don't think box-shadow is supported in ios mail app, I tested it with rgba colors and it's not showing

**Comment by strawberry3269** [comment]
您的邮件已收到， ~~~

**Comment by hteumeuleu** [comment]
Can you share your test code and which ESP you used to send your email? I'm seeing no issue with Can I email’s test code (https://www.caniemail.com/tests/css-box-shadow.html) on device sent with Parcel and on Email on Acid (https://app.emailonacid.com/app/acidtest/NQxqoXXlGl1K7NVQorVnp94zUXd4S5xxHrRycJlYG7juj/list).

**Comment by hithamalbasheir** [comment]
Hi @hteumeuleu , seems I got confused between the iOS mail app and gmail app, I got the screenshot thinking it was from mail app, so sorry for the confusion, and nice work on the website, it has been a lifesaver on email templates 🙏
![IMG-20240619-WA0004](https://github.com/hteumeuleu/caniemail/assets/38975111/1bde972a-544f-4dd2-98a4-f7318f1085ee)
I thought this image belonged to mail app from iOS
