### ISSUE TITLE
<style> element not supported in new Outlook

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [hteumeuleu/caniemail#440]
https://www.caniemail.com/features/html-style/

The following HTML content was formatted properly in Outlook and GMail. However, in the new Outlook, the `<style>` element seems to be completely ignored as that table is displayed without any styling. Even wrapping the `<style>` element into the `<head>` doesn't help here.

```html
<style>
  table, th, td {border: 1px solid black; border-collapse: collapse;}
  th, td {padding: 5px 10px;}
  .ok {background-color:green;}
  .warning {background-color: orange;}
  .error {background-color: red}
</style>
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td class='ok'></td>
    </tr>
    <tr>
      <td>2</td>
      <td class='warning'></td>
    </tr>
  </tbody>
</table>
```

**Comment by hteumeuleu** [comment]
Hi there. Could you give more details? I can not reproduce this in Outlook on Windows version `1.2024.313.100`. 

![Screenshot showing Outlook number version](https://github.com/user-attachments/assets/b1e46d93-cced-4796-b82d-a2021871411f)

![Screenshot showing the email displaying properly](https://github.com/user-attachments/assets/49b37827-ae99-4ea9-a1b4-c9d2e90f8bd1)
