### ISSUE TITLE
Is CanItMatrix still maintained?

### ISSUE THREAD

**Issue by TheJanzap** [hteumeuleu/caniemail#442]
I've just stumbled on CanItMatrix and it seems like a great resource on different Matrix clients and servers.
Unfortunately, it seems to me like the page hasn't been updated since 2021 based on the last added feature.
The [linked repo](https://github.com/matrix-org/canitmatrix) also hasn't had any commits since 2022.

So, since the footer of the page still links to this repo and because the canitmatrix repo has disabled GitHub Issues I wanted to ask here: Is CanItMatrix still maintained?

**Comment by hteumeuleu** [comment]
Hello there. I don't have anything to do and not related in any way with CanItMatrix. I think the site was forked from CanIEmail without ever changing the footer credits which unfortunately led you here. So there's nothing I can do for you. Good luck.
