### ISSUE TITLE
Tor/Socks Support (Addition Request)

### ISSUE THREAD

**Issue by Sazu-bit** [hteumeuleu/caniemail#457]
I'd like to compare which clients support proxy and tor natively... i.e. not through using something like torify. 

SchildiChat and Element support tor natively by offering a `--proxy` flag. You can use socks5://127.0.0.1:9050 and it'll do the rest.

**Comment by hteumeuleu** [comment]
Thank you for your submission but I don't feel this is part of the scope of this project.
