### ISSUE TITLE
support for <section> tags when email is forwarded

### ISSUE THREAD

**Issue by jgammel** [hteumeuleu/caniemail#477]
Is this the right place to request an update to this page: https://www.caniemail.com/search/?s=section

`<section>` tags are indeed partially supported by most clients, but this is not true when the email is forwarded. Gmail web app immediately replaces `<section> `tags with `<div> `and strips out all inline styles. 

If any project maintainers can confirm that this is a problem for forwarded emails, I request that the copy for Note 2 be updated to mention the forwarding problem.

**Comment by hteumeuleu** [comment]
A whole lot of things happen when forwarding an email (see https://www.hteumeuleu.com/2016/super-mail-forward-an-email-that-evolves-as-you-forward-it/). I consider email forward rendering a discipline of its own. It could deserve its own site (caniforward?). As such, I'd prefer not having any notes about forwarding on caniemail. Thanks for your comprehension.
