### ISSUE TITLE
Submit buttons in Outlook for Mac

### ISSUE THREAD

**Issue by thefunkybassist** [hteumeuleu/caniemail#53]
`<input type="submit">` are shown as functional in all versions of Outlook for Mac but according to my tests this is not the case! Submit buttons simply do nothing so a fallback needs to be used without a form submit for this client.

**Comment by hteumeuleu** [comment]
Do you have an example of your code that is not working? Maybe @M-J-Robbins can help on this one.

**Comment by M-J-Robbins** [comment]
Yes these should be listed as partial or failed support, the element renders but does not function.

Same issue for `<button type="submit">`

**Comment by M-J-Robbins** [comment]
Looks like it was logged wrong in my initial notes too, so think this one is my bad.

**Comment by thefunkybassist** [comment]
okay we were starting to doubt ourselves lol

**Comment by hteumeuleu** [comment]
[Fixed](https://github.com/hteumeuleu/caniemail/commit/9b4303cd85165dc18476879aa10e0e8254d8bd35). Thank you both for your help.
