### ISSUE TITLE
Add letter-spacing

### ISSUE THREAD

**Issue by sambeevors** [hteumeuleu/caniemail#61]
Love this resource, would be great to have information on `letter-spacing` too

**Comment by hteumeuleu** [comment]
There you go! https://www.caniemail.com/features/css-letter-spacing/

**Comment by hteumeuleu** [comment]
There you go! https://www.caniemail.com/features/css-letter-spacing/ Thanks for submitting this request. I'll close the issue. Feel free to reopen if you feel your request isn't fully answered.
