### ISSUE TITLE
Add more email clients

### ISSUE THREAD

**Issue by hteumeuleu** [hteumeuleu/caniemail#65]
Add features tests for more email clients:

- [x] Gmail (mobile webmail)
- [x] ProtonMail (desktop webmail, iOS, Android)
- [x] Mail.ru (desktop webmail)
- [x] Fastmail (desktop webmail)
- [ ] [SparkMail](https://sparkmailapp.com) (macOS, iOS, Android)
- [x] Gmx.de (desktop webmail, [iOS](https://apps.apple.com/fr/app/gmx-mail-cloud/id417352269), [Android](https://play.google.com/store/apps/details?id=de.gmx.mobile.android.mail&hl=en_US))
- [x] T-online.de (desktop webmail)

**Comment by hteumeuleu** [comment]
Added Gmail (mobile webmail) today. https://github.com/hteumeuleu/caniemail/commit/244b9f84db7008a88038cdb268484e3579995ef5

**Comment by hteumeuleu** [comment]
Added ProtonMail (desktop webmail, iOS, Android) today.

**Comment by hteumeuleu** [comment]
Added Mail.ru (desktop webmail) yesterday.

**Comment by jag-k** [comment]
Add Yandex Mail (Web, iOS, Android)

**Comment by neilj** [comment]
Awesome project! We at [Fastmail](https://www.fastmail.com) would be very happy to have our client included in the data set; let me know if we can help you out with a free account or something. (Our web and iOS/Android apps have identical HTML/CSS support, so only one entry is needed.)

**Comment by hteumeuleu** [comment]
@neilj Thank you! I'd love an account to test things out. Could you send me an email to _remi at hteumeuleu dot fr_ so we can sort this out?

**Comment by hteumeuleu** [comment]
[x] Added Fastmail (desktop webmail)

Thanks @neilj for the test account!

**Comment by husseinalhammad** [comment]
Shortwave may be worth adding. It may pick up a lot of users quickly given it brings a lot of Google Inbox features back:

https://www.shortwave.com/

https://arstechnica.com/gadgets/2022/02/ex-googlers-resurrect-google-inbox-interface-as-shortwave-email/

**Comment by hteumeuleu** [comment]
GMX.de and T-online.de have been added last month: https://www.caniemail.com/news/2022-12-30-december-updates/

**Comment by hteumeuleu** [comment]
Putting this on old for now.
