### ISSUE TITLE
When clicking on the % sign link in the units page results in a 400 - bad request

### ISSUE THREAD

**Issue by SprayCanMan** [hteumeuleu/caniemail#84]
Navigate to the following page:
https://www.caniemail.com/news/2020-02-25-css-units/

Then click on the % sign in the list of units, it will take you to the following link which gives a 400 error.  Most likely due to the fact that the %sign was not properly encoded in the URL:
https://www.caniemail.com/features/css-unit-%/

**Comment by hteumeuleu** [comment]
Nice catch. @M-J-Robbins fixed it. Thank you both!
