### ISSUE TITLE
Calling out VML solutions when CSS isn't supported

### ISSUE THREAD

**Issue by jkupczak** [hteumeuleu/caniemail#97]
Is there some way that we can call out VML as a replacement solution under CSS properties like `background` and `background-image`?

**Comment by hteumeuleu** [comment]
Would a note be enough for this? Or do you have something else in mind?

Also, I'm a bit conflicted on this as VML is an image format (just like SVG), so advising to use VML would be just like saying "use an image instead". Is that a good advice to give? (it's an open question, I honestly don't have an answer)

**Comment by jkupczak** [comment]
I think it's a little different than saying "use an image instead" because you can lay live text over the top of VML.

I think a note would be enough. Explain that VML is a viable alternative. I think a link to a resource would be helpful too, but I'm not sure where.

**Comment by hteumeuleu** [comment]
Good point on using live text. I've added a note on `background-image` : https://www.caniemail.com/features/css-background-image/

Does that fit what you had in mind?
Do you have a list a features like this that could be replicated using VML? I'm thinking about `border-radius` and `background-position` and `background-size`. Anything else?

**Comment by hteumeuleu** [comment]
I've added notes about VML solutions for [border-radius](https://www.caniemail.com/features/css-border-radius/),  [background-size](https://www.caniemail.com/features/css-background-size/), [background-origin](https://www.caniemail.com/features/css-background-origin/), [background-position](https://www.caniemail.com/features/css-background-position/), [background-repeat](https://www.caniemail.com/features/css-background-repeat/). Feel free to reopen or create a new issue if you can think of something else.

https://github.com/hteumeuleu/caniemail/commit/168179b1df231c6417e50daeaa4f886ef90bb6e1
