### ISSUE TITLE
<hr>

### ISSUE THREAD

**Issue by tvjames2007** [hteumeuleu/caniemail#98]
I don't see < hr > in the list. Is it not recommended?
It seems usually supported, but with some possible Outlook caveats

**Comment by hteumeuleu** [comment]
Definitely recommend using it. I think you've already been given this on Slack, but otherwise check this post by @M-J-Robbins : https://www.goodemailcode.com/email-code/hr

**Comment by hteumeuleu** [comment]
This was added in september this year: https://www.caniemail.com/features/html-hr/
